version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root  # Run as root initially
    ports:
      - 8090:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    entrypoint: >
      /bin/sh -c "
      chown jenkins:jenkins /var/run/docker.sock &&
      /sbin/tini -- /usr/local/bin/jenkins.sh
      "

volumes:
  jenkins_home: