name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build All Services
      run: |
        docker-compose build
    
    - name: Run Unit Tests
      run: |
        for service in frontend productcatalogservice currencyservice; do
          cd src/$service
          echo "Running tests for $service"
          go test ./... || echo "Tests failed for $service"
          cd ../../
        done
      continue-on-error: true
    
    - name: Start Application
      run: |
        docker-compose up -d
        # Wait for services to be up
        sleep 60
    
    - name: Run End-to-End Tests
      run: |
        ./tests/e2e-test.sh
    
    - name: Stop Application
      run: |
        docker-compose down