name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
    
    - name: Build All Services
      run: |
        docker-compose build
    
    - name: Run Unit Tests
      run: |
        for service in frontend productcatalogservice currencyservice; do
          if [ -d "src/$service" ]; then
            cd src/$service
            echo "Running tests for $service"
            go test ./... || echo "Tests failed for $service"
            cd ../../
          fi
        done
      continue-on-error: true
    
    - name: Start Application
      run: |
        docker-compose up -d
        # Wait for services to be up
        sleep 60
    
    - name: Run End-to-End Tests
      run: |
        chmod +x tests/e2e-test.sh
        ./tests/e2e-test.sh
      continue-on-error: true
    
    - name: Stop Application
      run: |
        docker-compose down